#!/bin/sh
# Generate include/mdvic/wcwidth_table.h using awk + sort
# Usage: UNICODE_DIR=/path/to/unicode tools/gen_wcwidth.sh

set -eu

if [ -z "${UNICODE_DIR:-}" ]; then
  echo "Set UNICODE_DIR to directory containing UnicodeData.txt and EastAsianWidth.txt" >&2
  exit 1
fi

UD="$UNICODE_DIR/UnicodeData.txt"
EAW="$UNICODE_DIR/EastAsianWidth.txt"

if [ ! -f "$UD" ] || [ ! -f "$EAW" ]; then
  echo "Missing UnicodeData.txt or EastAsianWidth.txt in $UNICODE_DIR" >&2
  exit 1
fi

TMPDIR=${TMPDIR:-/tmp}
comb_raw="$TMPDIR/mdvic_combining.$$"
wide_raw="$TMPDIR/mdvic_wide.$$"
comb_merged="$TMPDIR/mdvic_combining_merged.$$"
wide_merged="$TMPDIR/mdvic_wide_merged.$$"
trap 'rm -f "$comb_raw" "$wide_raw" "$comb_merged" "$wide_merged"' EXIT INT HUP

awk -v MODE=unicode -f "$(dirname "$0")/gen_wcwidth.awk" "$UD" | sort -n -k1,1 > "$comb_raw"
awk -v MODE=eaw     -f "$(dirname "$0")/gen_wcwidth.awk" "$EAW" | sort -n -k1,1 > "$wide_raw"

awk -f "$(dirname "$0")/merge_ranges.awk" "$comb_raw" > "$comb_merged"
awk -f "$(dirname "$0")/merge_ranges.awk" "$wide_raw" > "$wide_merged"

OUT="include/mdvic/wcwidth_table.h"
mkdir -p "$(dirname "$OUT")"
{
  echo "/* Auto-generated by tools/gen_wcwidth.sh. Do not edit by hand. */"
  echo "#ifndef MDVIC_WCWIDTH_TABLE_H"
  echo "#define MDVIC_WCWIDTH_TABLE_H"
  echo "#include <stdint.h>"
  echo "struct interval { uint32_t first; uint32_t last; };"
  echo
  echo "static const struct interval mdvic_combining[] = {"
  awk '{ printf("    {0x%04X,0x%04X},\n", $1, $2) }' "$comb_merged"
  echo "};"
  echo "#define MDVIC_COMBINING_COUNT (sizeof(mdvic_combining)/sizeof(mdvic_combining[0]))"
  echo
  echo "static const struct interval mdvic_wide[] = {"
  awk '{ printf("    {0x%04X,0x%04X},\n", $1, $2) }' "$wide_merged"
  echo "};"
  echo "#define MDVIC_WIDE_COUNT (sizeof(mdvic_wide)/sizeof(mdvic_wide[0]))"
  echo
  echo "#endif /* MDVIC_WCWIDTH_TABLE_H */"
} > "$OUT"

echo "Generated $OUT"

